=== GispoCoding/eip-peltomappi/src/peltomappi/subproject.schema.json
{
  "$schema": "http://json-schema.org/draft-07/schema",
  "type": "object",
  "properties": {
    "id": {
      "type": "string",
      "format": "uuid",
      "description": "unique identifier of the subproject"
    },
    "name": {
      "type": "string",
      "description": "name of the project in the Mergin Maps server"
    },
    "path": {
      "type": "string",
      "description": "path to the local folder containing the subproject"
    },
    "fieldParcelIds": {
      "type": "array",
      "description": "list of the field parcel IDs included in this project",
      "minItems": 1,
      "items": {
        "minLength": 10,
        "maxLength": 10,
        "type": "string"
      },
      "uniqueItems": true
    },
    "created": {
      "type": "string",
      "format": "date-time",
      "description": "timestamp of when subproject was created"
    },
    "modified": {
      "type": "array",
      "items": {
        "type": "object",
        "properties": {
          "modificationType": {
            "enum": [
              "PROJECT_UPDATE",
              "WEATHER_UPDATE"
            ],
            "type": "string",
            "description": "type of modification action"
          },
          "datetime": {
            "type": "string",
            "format": "date-time",
            "description": "when modification occured"
          }
        },
        "required": [
          "modificationType",
          "datetime"
        ]
      },
      "uniqueItems": true
    },
    "compositionId": {
      "type": "string",
      "format": "uuid",
      "description": "identifier of composition this subproject belongs to"
    }
  },
  "required": [
    "name",
    "fieldParcelIds"
  ]
}

=== GispoCoding/eip-peltomappi/test/testdata/test_subproject_with_data/peltomappi_subproject.json
{
  "id": "0069d09b-890a-4d1a-8922-d3b0fc8342b1",
  "name": "test_subproject_3",
  "fieldParcelIds": [
    "1111111111"
  ],
  "created": "1971-01-01T00:00:00+00:00",
  "compositionId": "aecea423-a08a-4a33-8a11-18dfb13f171c",
  "modified": [
    {
      "modificationType": "PROJECT_UPDATE",
      "datetime": "1971-01-02T00:00:00+00:00"
    },
    {
      "modificationType": "WEATHER_UPDATE",
      "datetime": "1971-01-03T00:00:00+00:00"
    }
  ]
}
